clone_folder: c:\gopath\src\github.com\Bios-Marcel\cordless

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
build: off
stack: go 1.13

artifacts:
  - path: cordless.exe
    name: cordless.exe

build_script:
  - go get -v -d ./...
  - go build -o cordless.exe

test_script:
  - go vet ./...
  - go test ./...
