name: Build
on: push
jobs:
  tests-and-builds:
    name: Tests and builds
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Go 1.12 build Mac OS
        uses: actions/setup-go@v1
        with:
          version: 1.12

      - name: Checkout master
        uses: actions/checkout@master

      - name: Run tests
        env:
          GO111MODULE: on
        run: go test ./...

      - name: Run build
        env:
          GO111MODULE: on
        run: go build .
